### ISSUE TITLE
你学的php太老了,有些笔记总结不对

### ISSUE THREAD

**Issue by buffge** [demon90s/CodingLab#1]
比如 http://lovemiemie.xyz/Blog/2021/04/12/%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95-20210412/
里面的总结 "PHP可以访问外部路径的文件，但可能没有权限去写。而且访问方式可能要使用相对路径。" 就是不对的
权限不是php的问题 是linux目录的权限问题,并且绝对路径和相对路径都是可以的.

顺便说一句 你的写笔记方式和我一模一样,写得比我还详细 你真的勤奋

**Comment by demon90s** [comment]
谢谢
